import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nunitoSans = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
		<head>
			<link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v6.1.1/css/pro.min.css" />
		</head>
      	<body className={nunitoSans.className}>
			<Nav />
			{children}
			<Footer />
		</body>
    </html>
  )
}
